# Generated by Django 5.2.5 on 2025-08-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=25)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('description', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('icon', models.CharField(max_length=10)),
            ],
        ),
    ]
